name: CI

on:
  pull_request:
  push:
  release:
    types: [published]

env:
  IMAGE_ID: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm i